services:
  # app:
  #   build: .
  #   ports: 
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app
  db:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=nest 
